apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-name
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-name
    app.kubernetes.io/part-of: go-application-sample
  name: test-component-name
  namespace: test
spec:
  path: /
  port:
    targetPort: "8081"
  to:
    kind: Service
    name: test-component-name
    weight: null
status: {}
